# .github/workflow/packer-pipeline.yml

name: Packer GCP Image Build

on:
  push:
    branches:
      - main
    tags:
      - '*'  # This triggers the workflow on any tag push
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Check GCP Authentication
      - name: Check GCP Authentication
        run: |
          gcloud auth list
          gcloud config list

      # Install Packer
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.9.1/packer_1.9.1_linux_amd64.zip
          unzip packer_1.9.1_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version

      # Initialize Packer
      - name: Initialize Packer
        run: |
          packer init .
      - name: Checking working directory
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/variables.pkrvars.hcl
      # Validate Packer configuration
      - name: Validate Packer
        run: |
          packer validate -var-file=variables.pkrvars.hcl .

      # Build Packer image
      - name: Build Packer
        run: |
          packer build -var-file=variables.pkrvars.hcl .
