# .github/workflow/packer-pipeline.yml

name: Packer GCP Image Build

on:
  push:
    branches:
      - main
    tags:
      - '*'  
  pull_request:
    branches: 
      - main

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up Google Cloud SDK
      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}

      # # Checking GCP Authentication
      # - name: Check GCP Authentication
      #   run: |
      #     gcloud auth list
      #     gcloud config list

      # Installing Packer
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.9.1/packer_1.9.1_linux_amd64.zip
          unzip packer_1.9.1_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version

      # Packer init
      - name: Initialize Packer
        run: |
          packer init .
      # Packer validate 
      - name: Validate Packer
        run: |
          packer validate -var-file=variables.pkrvars.hcl .

      # Packer build
      - name: Build Packer
        run: |
          packer build -var-file=variables.pkrvars.hcl .
